version: "3"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=AComplexPassword:ItShouldMeetRequirements!!!"
      - "MSSQL_PID=Express"
    ports:
      - "1433:1433"
    volumes:
      - ./sql:/sql
