version: "3"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - ./sql:/sql
      - ./scripts:/scripts
      - ./output:/output
